import { LoanInput } from './types';

export const LOAN_TEMPLATES: Record<string, Partial<LoanInput> & { label: string }> = {
  personal: {
    label: 'Préstamo Personal',
    amount: 10000,
    annualInterestRate: 8.99,
    termMonths: 84,
    openingFeeType: 'percent',
    openingFeeValue: 3.95,
    isOpeningFeeFinanced: true,
    insuranceSinglePremium: 0,
    isInsuranceFinanced: true,
    recurringMonthlyCosts: 0,
  },
  vehicle: {
    label: 'Coche',
    amount: 20000,
    annualInterestRate: 6.5,
    termMonths: 72,
    openingFeeType: 'percent',
    openingFeeValue: 1.5,
    isOpeningFeeFinanced: true,
    insuranceSinglePremium: 0,
    isInsuranceFinanced: true,
    recurringMonthlyCosts: 0,
  },
  mortgage: {
    label: 'Hipoteca',
    amount: 150000,
    annualInterestRate: 3.5,
    termMonths: 360,
    openingFeeType: 'fixed',
    openingFeeValue: 0,
    isOpeningFeeFinanced: false,
    insuranceSinglePremium: 1000,
    isInsuranceFinanced: true,
    recurringMonthlyCosts: 20,
  },
  reforma: {
    label: 'Reforma',
    amount: 15000,
    annualInterestRate: 7.25,
    termMonths: 96,
    openingFeeType: 'percent',
    openingFeeValue: 2.0,
    isOpeningFeeFinanced: true,
    insuranceSinglePremium: 0,
    isInsuranceFinanced: true,
    recurringMonthlyCosts: 0,
  },
};
